[package]
name = "konfiscator"
version = "0.1.0"
authors = ["Sevag Hanssian <sevag.hanssian@gmail.com>"]

[lib]
name = "konfiscator"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"
nix = "0.9"

[features]
default = ["sbrk"]
sbrk = []
mmap = []
